/**
 *This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
 *Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
 */

package
{
	import flash.display.Sprite;
	
	import flexUnitTests.VPaidTestSuite;
	import flexUnitTests.VpaidTest;
	
	public class FlexUnitCompilerApplication extends Sprite
	{
		private var flexUnitTests_VpaidTest_obj:flexUnitTests.VpaidTest;
		
		private var flexUnitTests_VPaidTestSuite_obj:flexUnitTests.VPaidTestSuite;
	}
}